### ISSUE TITLE
Blank Track

### ISSUE THREAD

**Issue by davidtonge** [treehouse/ios-issues#15]
There seems to be a blank track showing up next to the Ruby track. I'm guessing that's a placeholder for the Java track.

**Comment by mwhuss** [comment]
Thanks, I'll look into it tomorrow.

**Comment by abijlani** [comment]
@davidtonge I tried a fix, let me know if that worked.

**Comment by davidtonge** [comment]
Still seems to be there. I attached a picture.

![image1](https://cloud.githubusercontent.com/assets/5899196/5708049/cdfb32d2-9a5b-11e4-8102-ae2c649ffb33.png)

**Comment by mwhuss** [comment]
@davidtonge I'm wondering if it's some cached data. Could you delete the app and re-install. There's no need to sign out and back in.

**Comment by davidtonge** [comment]
Yep! Deleting the app and reinstalling fixed the problem @mwhuss.

**Comment by mwhuss** [comment]
http://bukk.it/fur-sure.gif
