### ISSUE TITLE
Offline Viewing - Can't sign in

### ISSUE THREAD

**Issue by AlexHedley** [treehouse/ios-issues#16]
When the login session times out you are unable to log back into the app.
I've already got downloaded videos and am now unable to view them without an internet connection.
Whereas if you are already logged in you still have all the cached data and downloaded videos available to view.

**Comment by abijlani** [comment]
@AlexHedley sorry for the delay. I've added this request to our list of features. I can definitely see it as being an issue.

**Comment by AlexHedley** [comment]
Thank
