### ISSUE TITLE
Code Challenge - 1st Objective missing

### ISSUE THREAD

**Issue by AlexHedley** [treehouse/ios-issues#17]
The 1st Objective text is missing from each Code Challenge.
After that the next stages show.
Course: C# Basics

**Comment by benjakuben** [comment]
Hi @AlexHedley , can you include a link to the challenge and potentially a screenshot, too? I checked a C# CC and it looked fine to me. Thanks!

**Comment by AlexHedley** [comment]
It was happening on most of them, the right hand side where the question usually is just wasn't showing.
If I went to the site and got the question I could answer it in the app, then it would move onto the next question, but wouldn't always show the question text

https://teamtreehouse.com/library/c-basics/perform/if

![tt-cc](https://cloud.githubusercontent.com/assets/1573469/11372386/15112e80-92c5-11e5-8621-6b01511172f0.JPG)

**Comment by abijlani** [comment]
@AlexHedley thanks for reporting it. This issue has been resolved in the new build which we will send out tomorrow. I see that you are in our beta testers list so please test it out and report back when you receive it.

**Comment by AlexHedley** [comment]
Will do :)

**Comment by AlexHedley** [comment]
Working fine now :)

**Comment by abijlani** [comment]
Great! Thanks for testing!
