### ISSUE TITLE
No Android section in Library

### ISSUE THREAD

**Issue by AlexHedley** [treehouse/ios-issues#20]
17 on the website, 16 in the app

![image](https://cloud.githubusercontent.com/assets/1573469/12208180/20f7e882-b643-11e5-9171-bbc7d0dc9fb8.png)
![image](https://cloud.githubusercontent.com/assets/1573469/12208181/2118f3ba-b643-11e5-85a2-9ba0d6034eb3.png)
![image](https://cloud.githubusercontent.com/assets/1573469/12208182/211bba5a-b643-11e5-84ed-4656f894f234.png)

**Comment by AlexHedley** [comment]
Any news on the @abijlani?

**Comment by abijlani** [comment]
Unfortunately that's a restriction by Apple: http://tech.co/treehouse-ipad-app-2013-07

**Comment by AlexHedley** [comment]
That's pants!

**Comment by abijlani** [comment]
Lol, never heard that term before will have to start using it ;)
