### ISSUE TITLE
Feature Request: Teachers Notes in app

### ISSUE THREAD

**Issue by AlexHedley** [treehouse/ios-issues#21]
https://teamtreehouse.com/community/are-teachers-notes-such-as-links-available-while-using-the-treehouse-app

> Raymond LeDuc
> Are teachers notes such as links available while using the Treehouse app?

> I like using the Treehose app for some of the content, however I was wondering if there was a way to get the teachers notes from there such as related links to current lesson.? It is a bit of a pain to go back through the modules to find what I missed. I feel that would be a nice feature to add if it currently is not supported.

**Comment by abijlani** [comment]
@AlexHedley when in portrait mode you can view the teacher notes

**Comment by AlexHedley** [comment]
There's a portrait mode? :p
You learn something new every day! I tend to keep stuff in landscape.

Is this the same for the android app?

**Comment by mwhuss** [comment]
![](http://digitaltower.hardwareresources.com/skin/frontend/hr/digitaltower/images/rotateIpad.gif)

**Comment by abijlani** [comment]
@mwhuss 👋  😆 

@AlexHedley haha.. yep :) Yes it's the same for Android as well.

**Comment by AlexHedley** [comment]
I've missed your gifs @mwhuss!

**Comment by mwhuss** [comment]
![](http://gifs.joelglovier.com/thumbs-up/chuck-norris.gif)
