### ISSUE TITLE
Code Challenge Error

### ISSUE THREAD

**Issue by juliangutierrez68** [treehouse/ios-issues#24]
Been seeing this code challenge error on Ajax Basics course, I'm able to finish the coding challenge on the web version of Treehouse. I'm not sure if this is an error with the app or Treehouse since I have seen this error on treehouse.com.
Iphone 5 IOS 9.3.1
 
![treehouse-error](https://cloud.githubusercontent.com/assets/10578958/15237850/051d90e8-18a0-11e6-827e-df5a72099cb8.png)

**Comment by abijlani** [comment]
@juliangutierrez68 could you try again? I could not replicate this issue. It worked fine for me. 
![simulator screen shot may 16 2016 2 10 34 pm](https://cloud.githubusercontent.com/assets/425440/15298939/0cc4b402-1b70-11e6-966b-1cc2b22c185d.png)

**Comment by juliangutierrez68** [comment]
Seems to be working now @abijlani although the the pop up says I've earned a badge that I've had for a while now. 
![img_0508](https://cloud.githubusercontent.com/assets/10578958/15299388/26fd64fc-1b72-11e6-97ab-43fcb8576f5e.PNG)

**Comment by abijlani** [comment]
If you finish a stage then it should show you that you were awarded the badge.
