### ISSUE TITLE
Landscape Mode for Lesson Videos

### ISSUE THREAD

**Issue by juliangutierrez68** [treehouse/ios-issues#25]
Landscape mode seems to work for workshop videos but not the actual lesson videos. I noticed updated notes include "enables rotation for the Bonus videos" has this not been enabled for lesson videos?
Iphone 5 IOS 9.3.1

**Comment by abijlani** [comment]
@juliangutierrez68  I just sent updated version can you check to see if this problem still exists. Thanks!

**Comment by juliangutierrez68** [comment]
@abijlani yup works after the update. Is there going to be a way to pause and play the video while in landscape orientation?

**Comment by abijlani** [comment]
@juliangutierrez68 yeah I have made that fix so the control bar appears in the bottom. We might change that up later.
