### ISSUE TITLE
Downloaded videos cause course to reorder

### ISSUE THREAD

**Issue by AlexHedley** [treehouse/ios-issues#26]
When I download videos for a course it reorders the lessons.

![image](https://cloud.githubusercontent.com/assets/1573469/15272724/92e63d72-1a7a-11e6-9dc1-ab6494d83eda.png)
![image](https://cloud.githubusercontent.com/assets/1573469/15272725/92f9b19a-1a7a-11e6-8c19-c261d69a2625.png)
![image](https://cloud.githubusercontent.com/assets/1573469/15272727/93156502-1a7a-11e6-9b0e-60f3222de52f.png)
![image](https://cloud.githubusercontent.com/assets/1573469/15272728/9316f21e-1a7a-11e6-968e-6b6113c3687e.png)
![image](https://cloud.githubusercontent.com/assets/1573469/15272729/931a0e04-1a7a-11e6-98fd-630e7495df8a.png)
![image](https://cloud.githubusercontent.com/assets/1573469/15272730/931bbbbe-1a7a-11e6-9b8c-96d6f22cf576.png)
![image](https://cloud.githubusercontent.com/assets/1573469/15272731/931e1a58-1a7a-11e6-8743-d03457a429a5.png)

**Comment by AlexHedley** [comment]
There's no prompt when deleting, maybe an are you sure?

Also the app crashed a number of times just when initially opening.

**Comment by abijlani** [comment]
@AlexHedley thanks! I've added it to the list of bug fixes.
