### ISSUE TITLE
Crashes when i join a track

### ISSUE THREAD

**Issue by riteshram** [treehouse/ios-issues#27]
When i select the join track option it loads up other courses for example if i try to join the iOS Development with Swift track it loads up all the other course like python, ruby etc(Screenshot 2).. Again if i touch the join track option the app crashes. 

Steps to Reproduce:-
1. Select any track
2. Click the join track option on top
3. Other courses loads up
4. Click the join track option again & the app crashes.

![img_1554](https://cloud.githubusercontent.com/assets/16020629/15309817/d48fe82a-1c07-11e6-87ba-f5e09468af34.PNG)
Other courses load i try to join track,
![img_1555](https://cloud.githubusercontent.com/assets/16020629/15309818/d748857c-1c07-11e6-9c02-107a43235ad3.PNG)

**Comment by abijlani** [comment]
Thanks. I do see the crash in Crashlytics. We will get this fixed.
