### ISSUE TITLE
Mute isn't adhered too

### ISSUE THREAD

**Issue by AlexHedley** [treehouse/ios-issues#30]
I was testing the encoding issue and with mute on the sounds were still playing

**Comment by AlexHedley** [comment]
3.0 (3591)
3.1 (3729)

iOS 10 - iPhone

**Comment by abijlani** [comment]
That is deliberate because students kept complaining that there was no sound with the video. A tech savvy user knows to look for the mute button but seems like that was not obvious to most.

**Comment by mwhuss** [comment]
Oh I remember that 😂

**Comment by AlexHedley** [comment]
Ah, slyly testing at work was nearly noticed :p
I'll just plug my headphones in

**Comment by abijlani** [comment]
![](http://media.tumblr.com/tumblr_m8jnvliqtz1r7qsdw.gif)
